# Generated by Django 3.1.4 on 2021-01-27 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srcApp', '0002_auto_20210125_0737'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
