# Generated by Django 3.1.4 on 2021-02-10 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srcApp', '0010_auto_20210210_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
