# Generated by Django 3.1.4 on 2021-02-10 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcApp', '0011_auto_20210210_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=150, unique=True),
        ),
    ]
